import Head from "next/head";
import Image from "next/image";
import Axios from "axios";
import Feeds from "../components/Feeds";
import Header from "../components/Header";
import React, { useState } from "react";

export default function Home({ data }) {
  const [isLoading, setIsLoading] = useState(true)
    if (isLoading)
      return (
        <div className="">
          {/* <Spinner className="spinner-icon" /> */}
          <h1>loading...</h1>
        </div>
      );
  return (
    <div>
      <Head>
        <title>Spacestagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
      <main>
        {data.map((d) => (
          <div key={d.date} className="ml-5">
            <Feeds url={d.url} explanation={d.explanation} />
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  setIsLoading(true);
  const { data } = await Axios.get(
    `https://api.nasa.gov/planetary/apod?api_key=${process.env.NEXT_PUBLIC_API_KEY}&count=5`
  );
  console.log(data);
  
  setIsLoading(false)
  return {
    props: {
      data,
    },
  };
}
